### PR TITLE
Have git ignore save files

### PR DESCRIPTION
**Pull request by 10220**
First pull request!!! 

You'll notice that I make a fork of your repo, so now there exists a copy of your repo hosted by me ([here](https://github.com/10220/adventures)). This copy I can make edits to without affecting yours, and if you add more commits then I can pull them over to my fork. If I make a change in my fork that I think you might like then I can submit a pull request (PR) as I am doing now. I have made a commit and I am making a request for you to pull my commit into your repo. 

What I am doing is removing the `names.txt` file that is being tracked by github. I am also adding a file callled `.gitignore`. Git knows to look for this file and whatever is listed there will be ignored. This means you can make multiple save files and git will just ignore them. 

Click on the tabs above to explore what I am adding. Instead of just merging this, try to formally request a change. You can add a comment to a like of my code and then click the Review Changes button to either just leave a comment, approve the PR, or formally request a change.

### CODE REVIEW

**Comment by gatorfan95** [comment]
Why does one do these things? Is this how collaboratively working on a
file works? Why does Git need to ignore certain things?

**Comment by 10220** [comment]
This is essentially how open-source collaborative work takes place. For example, I was using someone else's python package that I found on Github and I discovered a bug in the code. I could have just submitted a bug report, but since I also knew how to fix the bug I just figured I would save the person some time and submit a pull request for the fix. Another reason for the pull request is that our collaboration has it's own Github account and so if anyone wants to get their new code into master, then we have to submit a pull request. 

As for the `.gitignore` file, there are many reasons why you may want to ignore a local file. In this case, pretend that locally you will keep running the script and the save file `names.txt` will keep being updated. Well you wouldn't necessarily want to keep adding these changes as a commit because this is just a local save file. But it might get annoying to keep seeing Git saying that `names.txt` is an untracked file, so to clean things up we can add it to `.gitignore`. In short, any file that is only needed locally and doesn't necessarily need to clutter up the repo then add it to the `.gitignore` ;)

**Comment by 10220** [comment]
Oh you can also use the wildcard `*` in the `.gitignore`. So let's say I have a script that will generate 10 datafiles names `data_0.dat`, `data_1.dat`, etc. Then we can just put the following line in `.gitignore` to ignore all of them:
```
*.dat
```
or to be more specific
```
data_*.dat
```

**Comment by gatorfan95** [comment]
I'll be taking my mom to PA on Sunday after Mass... any more homework?

**Comment by 10220** [comment]
Yup, here is the next assignment! But since you'll be on the road don't worry about the Sunday deadline, just work on this at your leisure for now and after Thanksgiving we'll check back in on this :)

1. If you think you want to ignore the `names.txt` file, then merge this pull request by clicking the merge button, otherwise close this PR.
1. Take the code that performs the save and move that into it's own function since it might be called often. 
1. Have the script check if there is a save file and load the story from the save point (so at least it can recall your name for how it's currently written), if not then the script starts from the beginning.

**Pull request merged**
